workspace = { members = ["src/lib"] }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "fast-blur"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fast-blur"
path = "src/main.rs"

[dependencies]
colorutils-rs = "0.4.9"
half = "2.4.1"
image = "0.25.1"
libblur = {path = "src/lib"}
rayon = "1.10.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "gauss_bench"
harness = false

[[bench]]
name = "stack_blur"
harness = false

[[bench]]
name = "fast_gaussian"
harness = false
